// src/detection/hookSetup.js
// Optional Layer 1: Hook-based IPC using Claude Code's lifecycle hooks.
//
// When enabled, this module:
// 1. Writes a small shell script to ~/.claude/hooks/
// 2. Injects hook configuration into ~/.claude/settings.json
// 3. Watches a temp state file for signals from the hook
//
// The hook fires on Claude Code's "Notification" and "Stop" events,
// providing the most reliable possible pause detection signal.
//
// This is entirely optional — the PauseDetector works without it.

import fs from 'fs';
import path from 'path';
import os from 'os';

const HOOK_SCRIPT_NAME = 'remote-claude-notify.sh';
const SETTINGS_PATH = path.join(os.homedir(), '.claude', 'settings.json');

/**
 * Get the path where hook state signals are written.
 * @param {string} channelId - Unique session identifier.
 * @returns {string} Absolute path to the state file.
 */
export function getStateFilePath(channelId) {
  const tmpDir = path.join(os.tmpdir(), 'remote-claude');
  if (!fs.existsSync(tmpDir)) {
    fs.mkdirSync(tmpDir, { recursive: true });
  }
  return path.join(tmpDir, `${channelId}.state`);
}

/**
 * Install the Claude Code hook for remote-claude.
 * Creates the hook script and adds it to settings.json.
 *
 * @param {string} channelId - Session channel ID for the state file.
 * @returns {{ stateFilePath: string, cleanup: Function } | null}
 *   Returns the state file path and a cleanup function, or null on failure.
 */
export function installHook(channelId) {
  try {
    const stateFilePath = getStateFilePath(channelId);
    const hookDir = path.join(os.homedir(), '.claude', 'hooks');

    // ── Step 1: Write the hook shell script ──
    fs.mkdirSync(hookDir, { recursive: true });
    const hookScriptPath = path.join(hookDir, HOOK_SCRIPT_NAME);

    // The hook script receives the event type as $1 and writes it
    // to the state file. It must drain stdin (Claude sends JSON via stdin).
    const hookScript = `#!/bin/bash
# Auto-generated by remote-claude. Safe to delete.
# Signals Claude Code lifecycle events to the remote-claude CLI.
cat > /dev/null 2>&1 || true
STATE_FILE="${stateFilePath}"
EVENT_TYPE="\${1:-unknown}"
echo "$EVENT_TYPE" > "$STATE_FILE"
exit 0
`;

    fs.writeFileSync(hookScriptPath, hookScript, { mode: 0o755 });

    // ── Step 2: Inject into ~/.claude/settings.json ──
    const injected = _injectHookConfig(hookScriptPath);

    if (injected) {
      console.log('\x1b[32m[remote-claude] ✓ Claude Code hook installed for precise pause detection.\x1b[39m');
    } else {
      console.log('\x1b[33m[remote-claude] ⚠ Could not auto-configure hooks. Falling back to pattern detection.\x1b[39m');
    }

    // Return cleanup function to remove our hook on exit
    const cleanup = () => {
      try {
        if (fs.existsSync(stateFilePath)) fs.unlinkSync(stateFilePath);
        // Don't remove the hook script or settings entries on exit —
        // they're harmless and the user might want to keep them.
      } catch (_) {
        // Ignore cleanup errors
      }
    };

    return { stateFilePath, cleanup };
  } catch (err) {
    console.log(`\x1b[33m[remote-claude] Hook setup skipped: ${err.message}\x1b[39m`);
    return null;
  }
}

/**
 * Watch the state file for hook signals.
 * Returns a cleanup function to stop watching.
 *
 * @param {string} stateFilePath - Path to the state file.
 * @param {Function} onSignal - Called with the signal string (e.g. "Notification", "Stop").
 * @returns {Function} Cleanup function.
 */
export function watchStateFile(stateFilePath, onSignal) {
  // Use polling-based watch for reliability across platforms
  let lastContent = '';
  let lastMtime = 0;

  const interval = setInterval(() => {
    try {
      if (!fs.existsSync(stateFilePath)) return;
      const stat = fs.statSync(stateFilePath);
      if (stat.mtimeMs <= lastMtime) return;
      lastMtime = stat.mtimeMs;

      const content = fs.readFileSync(stateFilePath, 'utf8').trim();
      if (content && content !== lastContent) {
        lastContent = content;
        onSignal(content);
      }
    } catch (_) {
      // Ignore read errors — file might be being written
    }
  }, 500); // Check every 500ms

  return () => {
    clearInterval(interval);
  };
}

// ═══════════════════════════════════════════════════════════════
// PRIVATE: Settings injection
// ═══════════════════════════════════════════════════════════════

/**
 * Inject our hook entries into ~/.claude/settings.json.
 * Preserves existing hooks and only adds ours if not already present.
 */
function _injectHookConfig(hookScriptPath) {
  try {
    let settings = {};

    // Read existing settings
    if (fs.existsSync(SETTINGS_PATH)) {
      const raw = fs.readFileSync(SETTINGS_PATH, 'utf8');
      settings = JSON.parse(raw);
    } else {
      // Create the .claude directory if needed
      const claudeDir = path.dirname(SETTINGS_PATH);
      fs.mkdirSync(claudeDir, { recursive: true });
    }

    // Ensure hooks object exists
    if (!settings.hooks) {
      settings.hooks = {};
    }

    // Define the events we want to hook into
    const events = ['Notification', 'Stop'];
    let modified = false;

    for (const event of events) {
      const hookEntry = {
        matcher: '',
        hooks: [
          {
            type: 'command',
            command: `${hookScriptPath} ${event}`,
          },
        ],
      };

      if (!settings.hooks[event]) {
        settings.hooks[event] = [hookEntry];
        modified = true;
      } else {
        // Check if our hook is already there
        const alreadyInstalled = settings.hooks[event].some((entry) =>
          entry.hooks?.some((h) => h.command?.includes(HOOK_SCRIPT_NAME))
        );

        if (!alreadyInstalled) {
          settings.hooks[event].push(hookEntry);
          modified = true;
        }
      }
    }

    if (modified) {
      // Write back with a backup
      if (fs.existsSync(SETTINGS_PATH)) {
        const backupPath = SETTINGS_PATH + '.bak';
        fs.copyFileSync(SETTINGS_PATH, backupPath);
      }
      fs.writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2));
    }

    return true;
  } catch (err) {
    // Settings file might be read-only or malformed — don't crash
    return false;
  }
}
